build(release-workflow): Removed version step

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -82,17 +82,17 @@ jobs:
         run: |
           git remote -v
 
-      - name: Bump version
-        run: |
-          npm version ${{ env.VERSION_TYPE }}
-          NEW_VERSION=$(node -p "require('./package.json').version")
-          git commit --amend -m "chore(release): ${NEW_VERSION} version released" || echo "No commit to amend"
-          git push origin HEAD:${GITHUB_REF_NAME} --force > push_output.log 2>&1
-          if [ $? -ne 0 ]; then
-            echo "Git push failed. Here is the detailed output:"
-            cat push_output.log
-            exit 1
-          fi
+      # - name: Bump version
+      #   run: |
+      #     npm version ${{ env.VERSION_TYPE }}
+      #     NEW_VERSION=$(node -p "require('./package.json').version")
+      #     git commit --amend -m "chore(release): ${NEW_VERSION} version released" || echo "No commit to amend"
+      #     git push origin HEAD:${GITHUB_REF_NAME} --force > push_output.log 2>&1
+      #     if [ $? -ne 0 ]; then
+      #       echo "Git push failed. Here is the detailed output:"
+      #       cat push_output.log
+      #       exit 1
+      #     fi
 
       - name: Publish to npm
         env:
